export const actionTypes = {
    FETCH_POKEMON: 'FETCH_POKEMON',
    GET_POKEMON_TYPES: 'GET_POKEMON_TYPES',
    TOGGLE_POKEMON_MODAL_WINDOW: 'TOGGLE_POKEMON_MODAL_WINDOW',
    MAKE_API_REQUEST: 'MAKE_API_REQUEST',
    SELECT_POKEMON: 'SELECT_POKEMON',
    TOGGLE_DOWNLOAD_POKEMON_MODAL_WINDOW: 'TOGGLE_DOWNLOAD_POKEMON_MODAL_WINDOW'
}