export const actionTypes = {
    GET_ALL_POKEMON: 'GET_ALL_POKEMON',
    GET_POKEMON_TYPES: 'GET_POKEMON_TYPES',
    TOGGLE_POKEMON_MODAL_WINDOW: 'TOGGLE_POKEMON_MODAL_WINDOW',
    SELECT_POKEMON: 'SELECT_POKEMON',
    TOGGLE_DOWNLOAD_POKEMON_MODAL_WINDOW: 'TOGGLE_DOWNLOAD_POKEMON_MODAL_WINDOW'
}